services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: app_backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - LLM_TO_USE=${LLM_TO_USE}

  worker:
    build: .
    container_name: celery_worker
    command: celery -A app.core.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - REDIS_URL={REDIS_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - LLM_TO_USE=${LLM_TO_USE}
